name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
      
    - name: Install dependencies
      run: pip install -r ./backend/requirements.txt
      
    - name: Google Cloud Platform (GCP) CLI - gcloud
      uses: actions-hub/gcloud@272.0.0
      env:
        PROJECT_ID: triathlon-challenge
        APPLICATION_CREDENTIALS: ${{ secrets.APPLICATION_CREDENTIALS }}
      with:
        args: app deploy
    
